Issue/42/initialization
DarkEnergyScienceCollaboration/SLTimer pull request #59
Opened 2016-11-08 18:20 UTC by chto

I have implemented a method to include prior information into our plots. 
I also solve the flip sign problem between TDC2 and PyCS. For convenience, I adopt the convention defined in PyCS which means T_AB = T_A-T_B.

2016-11-09 19:33 UTC, chto commented
Hi @drphilmarshall , 
I have implemented a method to include prior information into our plots.
I also solve the flip a sign problem for time delay by adopting convention in PyCS team. 
Besides, I also implement a sigma_intrinsic to describe the extra noise. 
Could you review my code? Thanks.

2016-11-09 19:39 UTC, chto commented
Btw, It should also be able to merge to master branch. I solve the merge problem in my local machine.

2016-11-16 21:35 UTC, drphilmarshall commented
Great stuff! I'll review this on Thursday, when I am back.

On Wednesday, November 9, 2016, Chun-Hao To <notifications@github.com>
wrote:

> Btw, It should also be able to merge to master branch. I solve the merge
> problem in my local machine.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DarkEnergyScienceCollaboration/SLTimer/pull/59#issuecomment-259505831>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AArY99wAD_sYp6BtXU-Y5zQFLBhARQUCks5q8iF2gaJpZM4Ksvvr>
> .
>

2016-11-21 10:06 UTC, chto commented
Hi @drphilmarshall,
The code is ready for review.

2016-11-24 01:15 UTC, drphilmarshall requested changes
Some concern about new whitening, and whether it acts on magnitudes or fluxes...

2016-11-24 01:15 UTC, drphilmarshall commented on python/desc/sltimer/reading.py
> +                lcs[j].mags[np.intersect1d(index[band], season.indices)] -= offset[band]
Here, are you subtracting the mean magnitude or the mean flux? It looks like the mean magnitude. That's OK, we just have to be very clear about what we are doing, and what it means. Can you make sure the docstring of this method is correct, and as full as possible, please?

2016-11-24 01:21 UTC, drphilmarshall commented
I think we could merge this, after you tracked down the problem and switched to investigating $\sigma_{intrinsic}$. I think we will soon want to move the notebook you finished here into some sort of "attic" folder, and list the results with the better model as the package demo. We can do that later, though. For now, our coverage is failing! That means we are not writing enough unit tests. Can you think of some good ones based on your experience so far? 

> A good way to program is to write tests that would re-create bugs, if you hadn't fixed the code already. (Likewise, whenever you get a bug, first write the unit test that fails because of the bug, and then fix the code until the test passes.)

2016-12-01 01:11 UTC, drphilmarshall commented
Hey @chto - can you please turn off the stdout? It's making the notebooks very very long, and delaying the enjoyment of your new intrinsic sigma analysis plot :-)

2016-12-09 21:11 UTC, drphilmarshall commented
Hi @chto - I think you have moved well beyond the initialization problem now, so I have merged these commits into `issue/40/tdc2gatewaytest`, which is where we should write our LSST DESC Note on your and Milan's work.

2016-12-09 21:11 UTC, closed without merging